CREATE TABLE food_log (
id SERIAL PRIMARY KEY,
user_id VARCHAR(255) NOT NULL,
food_id VARCHAR(255) NOT NULL,
label VARCHAR(255) NOT NULL,
kcal INTEGER NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);